### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by svenstaro** [Eljay/assimp-sys#13]
> rustc -V
> rustc 1.13.0-nightly (4f9812a59 2016-09-21)
> cargo -V
> cargo 0.13.0-nightly (9399229 2016-09-14)

I got this in my Cargo.toml:

    [dependencies]
    assimp-sys = "*"

> error: failed to run custom build command for `assimp-sys v0.2.0`
> process didn't exit successfully: `/home/svenstaro/prj/myproject/target/debug/build/assimp-sys-66702068da0bdbb6/build-script-build` (exit code: 101)
> --- stdout
> running: "cmake" "/home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/assimp-sys-0.2.0/assimp" "-DASSIMP_BUILD_ASSIMP_TOOLS=OFF" "-DASSIMP_BUILD_TESTS=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DLIBRARY_SUFFIX=" "-DCMAKE_INSTALL_PREFIX=/home/svenstaro/prj/myproject/target/debug/build/assimp-sys-66702068da0bdbb6/out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_C_COMPILER=/usr/lib/hardening-wrapper/bin/cc" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_CXX_COMPILER=/usr/lib/hardening-wrapper/bin/c++"
> 
> --- stderr
> CMake Error: The source directory "/home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/assimp-sys-0.2.0/assimp" does not exist.
> Specify --help for usage, or press the help button on the CMake GUI.
> thread 'main' panicked at '
> command did not execute successfully, got: exit code: 1
> 
> build script failed, must exit now', /home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.17/src/lib.rs:463
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
>

**Comment by Eljay** [comment]
Should be fixed with version 0.2.1.

**Comment by svenstaro** [comment]
Yup works, thanks.

**Comment by svenstaro** [comment]
Alright so this is still not entirely fixed. This works:

    cargo test --release

However, cross-compiling fails like this:

    cargo test --target=x86_64-pc-windows-gnu --release

> error: failed to run custom build command for `assimp-sys v0.2.1`
> process didn't exit successfully: `/home/svenstaro/prj/myproject/target/release/build/assimp-sys-f88e4f1fcfc90af1/build-script-build` (exit code: 101)
> --- stdout
> running: "cmake" "/home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/assimp-sys-0.2.1/assimp" "-DCMAKE_SYSTEM_NAME=Windows" "-DCMAKE_RC_COMPILER=/usr/bin/x86_64-w64-mingw32-windres" "-DASSIMP_BUILD_ASSIMP_TOOLS=OFF" "-DASSIMP_BUILD_TESTS=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DLIBRARY_SUFFIX=" "-DCMAKE_INSTALL_PREFIX=/home/svenstaro/prj/myproject/target/x86_64-pc-windows-gnu/release/build/assimp-sys-f88e4f1fcfc90af1/out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m64" "-DCMAKE_C_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/x86_64-w64-mingw32-g++"
> 
> --- stderr
> fatal: Not a git repository (or any of the parent directories): .git
> CMake Error: The source directory "/home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/assimp-sys-0.2.1/assimp" does not exist.
> Specify --help for usage, or press the help button on the CMake GUI.
> thread 'main' panicked at '
> command did not execute successfully, got: exit code: 1
> 
> build script failed, must exit now', /home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.17/src/lib.rs:463
> stack backtrace:
>    1:     0x55ad379921ff - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
>    2:     0x55ad3799917d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
>    3:     0x55ad379980aa - std::panicking::default_hook::h852b4223c1c00c59
>    4:     0x55ad379985f8 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
>    5:     0x55ad37998492 - std::panicking::begin_panic::hf6c488cee66e7f17
>    6:     0x55ad379983d0 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
>    7:     0x55ad3797ff15 - cmake::fail::h730a08371de1f6e7
>    8:     0x55ad3797f8af - cmake::run::h6c9da7f8e1bbdbd3
>    9:     0x55ad3797e35d - cmake::Config::build::h4e21e813a380b3fb
>   10:     0x55ad37974222 - build_script_build::main::hc145c1bfabb67a9e
>   11:     0x55ad379a0c46 - __rust_maybe_catch_panic
>   12:     0x55ad37997921 - std::rt::lang_start::h14cbded5fe3cd915
>   13:     0x7f1ef46f2290 - __libc_start_main
>   14:     0x55ad379730b9 - _start
>   15:                0x0 - <unknown>
>

**Comment by Eljay** [comment]
Ok attempt 2, cargo really doesn't like git submodules. Version 0.2.2 should *actually* fix it.

**Comment by svenstaro** [comment]
Yes, seems to work now. Thanks!
